/* tslint:disable */
/* eslint-disable */
/**
 * KGH PROJECT API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ActivityLogDto
 */
export interface ActivityLogDto {
    /**
     * 
     * @type {number}
     * @memberof ActivityLogDto
     */
    'id'?: number;

    /**
     * 
     * @type {number}
     * @memberof ActivityLogDto
     */
    'requestId'?: number;
    /**
     * 
     * @type {number}
     * @memberof ActivityLogDto
     */
    'ordinalNumber'?: number;
    /**
     * 
     * @type {string}
     * @memberof ActivityLogDto
     */
    'userId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ActivityLogDto
     */
    'estimatedPickup'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ActivityLogDto
     */
    'estimatedDropoff'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ActivityLogDto
     */
    'cargo'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ActivityLogDto
     */
    'myPrice'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ActivityLogDto
     */
    'status'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof ActivityLogDto
     */
    'isActive'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ActivityLogDto
     */
    'isPending'?: boolean;
        /**
     * 
     * @type {boolean}
     * @memberof ActivityLogDto
     */
    'isRejected'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ActivityLogDto
     */
    'deadline'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ActivityLogDto
     */
    'user'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ActivityLogDto
     */
    'ip'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ActivityLogDto
     */
    'logTypeId'?: number;
    /**
     * 
     * @type {string}
     * @memberof ActivityLogDto
     */
    'logType'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ActivityLogDto
     */
    'activity'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ActivityLogDto
     */
    'description'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ActivityLogDto
     */
    'date'?: string | null;
}

