/* tslint:disable */
/* eslint-disable */
/**
 * KGH PROJECT API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AccessLevelType } from './access-level-type';
// May contain unused imports in some cases
// @ts-ignore
import { AssignUserToGroupDto } from './assign-user-to-group-dto';
// May contain unused imports in some cases
// @ts-ignore
import { UserGroupPermission } from './user-group-permission';

/**
 * 
 * @export
 * @interface AddUserGroupCommand
 */
export interface AddUserGroupCommand {
    /**
     * 
     * @type {string}
     * @memberof AddUserGroupCommand
     */
    'name'?: string | null;
    /**
     * 
     * @type {AccessLevelType}
     * @memberof AddUserGroupCommand
     */
    'accessLevel'?: AccessLevelType;
    /**
     * 
     * @type {string}
     * @memberof AddUserGroupCommand
     */
    'createdById'?: string | null;
    /**
     * 
     * @type {Array<AssignUserToGroupDto>}
     * @memberof AddUserGroupCommand
     */
    'users'?: Array<AssignUserToGroupDto> | null;
    /**
     * 
     * @type {Array<UserGroupPermission>}
     * @memberof AddUserGroupCommand
     */
    'permissions'?: Array<UserGroupPermission> | null;
}

