/* tslint:disable */
/* eslint-disable */
/**
 * KGH PROJECT API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { EquipmentDto } from './equipment-dto';

/**
 * 
 * @export
 * @interface BranchWithEquipmentsDetailsDto
 */
export interface BranchWithEquipmentsDetailsDto {
    /**
     * 
     * @type {string}
     * @memberof BranchWithEquipmentsDetailsDto
     */
    'name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BranchWithEquipmentsDetailsDto
     */
    'email'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BranchWithEquipmentsDetailsDto
     */
    'address'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BranchWithEquipmentsDetailsDto
     */
    'place'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BranchWithEquipmentsDetailsDto
     */
    'contactPerson'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BranchWithEquipmentsDetailsDto
     */
    'contactPhone'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BranchWithEquipmentsDetailsDto
     */
    'municipality'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BranchWithEquipmentsDetailsDto
     */
    'canton'?: string | null;
     /**
     * 
     * @type {string}
     * @memberof BranchWithEquipmentsDetailsDto
     */
     'equipmentsCount'?: number | null;
    
    /**
     * 
     * @type {string}
     * @memberof BranchWithEquipmentsDetailsDto
     */
    'entity'?: string | null;
    /**
     * 
     * @type {Array<EquipmentDto>}
     * @memberof BranchWithEquipmentsDetailsDto
     */
    'equipments'?: Array<EquipmentDto> | null;
}

