/* tslint:disable */
/* eslint-disable */
/**
 * KGH PROJECT API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CantonDto } from './canton-dto';

/**
 * 
 * @export
 * @interface CantonDtoPaginatedList
 */
export interface CantonDtoPaginatedList {
    /**
     * 
     * @type {Array<CantonDto>}
     * @memberof CantonDtoPaginatedList
     */
    'items'?: Array<CantonDto> | null;
    /**
     * 
     * @type {number}
     * @memberof CantonDtoPaginatedList
     */
    'pageIndex'?: number;
    /**
     * 
     * @type {number}
     * @memberof CantonDtoPaginatedList
     */
    'totalPages'?: number;
    /**
     * 
     * @type {number}
     * @memberof CantonDtoPaginatedList
     */
    'totalCount'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof CantonDtoPaginatedList
     */
    'hasPreviousPage'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CantonDtoPaginatedList
     */
    'hasNextPage'?: boolean;
}

