/* tslint:disable */
/* eslint-disable */
/**
 * KGH PROJECT API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CheckCertificateNumberAvailabilityQuery
 */
export interface CheckCertificateNumberAvailabilityQuery {
    /**
     * 
     * @type {Array<string>}
     * @memberof CheckCertificateNumberAvailabilityQuery
     */
    'certificationNumbers'?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof CheckCertificateNumberAvailabilityQuery
     */
    'organizationId'?: string | null;
}

