/* tslint:disable */
/* eslint-disable */
/**
 * KGH PROJECT API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CodebookDto
 */
export interface CodebookDto {
    /**
     * 
     * @type {string}
     * @memberof CodebookDto
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof CodebookDto
     */
    'name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CodebookDto
     */
    'internalCode'?: string | null;
}

