/* tslint:disable */
/* eslint-disable */
/**
 * KGH PROJECT API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const CodebookTypeEnum = {
    TypeOfTrailers: 1,
    Countries: 2,
    OperatingCountries: 3,
    CemtPermits: 4,
    Certificates: 5,
    Licenses: 6,
    GoodsType: 7,
    VehicleRequirements:8,
    Currency:9
} as const;

export type CodebookTypeEnum = typeof CodebookTypeEnum[keyof typeof CodebookTypeEnum];



