/* tslint:disable */
/* eslint-disable */
/**
 * KGH PROJECT API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateCertifiedTechnicianDto
 */
export interface CreateCertifiedTechnicianDto {
    /**
     * 
     * @type {string}
     * @memberof CreateCertifiedTechnicianDto
     */
    'firstName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateCertifiedTechnicianDto
     */
    'lastName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateCertifiedTechnicianDto
     */
    'email'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CreateCertifiedTechnicianDto
     */
    'languageId'?: number;
    /**
     * 
     * @type {string}
     * @memberof CreateCertifiedTechnicianDto
     */
    'organizationId'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCertifiedTechnicianDto
     */
    'placeOfBirth'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateCertifiedTechnicianDto
     */
    'birthDay'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CreateCertifiedTechnicianDto
     */
    'municipalityId'?: number;
    /**
     * 
     * @type {string}
     * @memberof CreateCertifiedTechnicianDto
     */
    'dateOfExam'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCertifiedTechnicianDto
     */
    'certificateNumber'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateCertifiedTechnicianDto
     */
    'certificateDuration'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCertifiedTechnicianDto
     */
    'qualificationTypeId'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCertifiedTechnicianDto
     */
    'comments'?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateCertifiedTechnicianDto
     */
    'userGroups'?: Array<string> | null;
    /**
     * 
     * @type {Array<File>}
     * @memberof CreateCertifiedTechnicianDto
     */
    'files'?: Array<File> | null;
}

