/* tslint:disable */
/* eslint-disable */
/**
 * KGH PROJECT API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface EmploymentHistoryDto
 */
export interface EmploymentHistoryDto {
    /**
     * 
     * @type {string}
     * @memberof EmploymentHistoryDto
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmploymentHistoryDto
     */
    'companyId'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmploymentHistoryDto
     */
    'companyName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EmploymentHistoryDto
     */
    'startDate'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EmploymentHistoryDto
     */
    'endDate'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof EmploymentHistoryDto
     */
    'isPresent'?: boolean;
}

