/* tslint:disable */
/* eslint-disable */
/**
 * KGH PROJECT API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { EquipmentActivityDto } from './equipment-activity-dto';
// May contain unused imports in some cases
// @ts-ignore
import { FileResultDto } from './file-result-dto';

/**
 * 
 * @export
 * @interface EquipmentDto
 */
export interface EquipmentDto {
    /**
     * 
     * @type {string}
     * @memberof EquipmentDto
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof EquipmentDto
     */
    'companyBranchId'?: string;
    /**
     * 
     * @type {string}
     * @memberof EquipmentDto
     */
    'branchOfficeName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EquipmentDto
     */
    'typeOfEquipmentId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EquipmentDto
     */
    'typeOfEquipment'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EquipmentDto
     */
    'typeOfEquipmentOther'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EquipmentDto
     */
    'typeOfCoolingSystemId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EquipmentDto
     */
    'typeOfCoolingSystem'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EquipmentDto
     */
    'typeOfCoolingSystemOther'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EquipmentDto
     */
    'manufacturer'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EquipmentDto
     */
    'type'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EquipmentDto
     */
    'model'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EquipmentDto
     */
    'serialNumber'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof EquipmentDto
     */
    'yearOfProduction'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof EquipmentDto
     */
    'dateOfPurchase'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EquipmentDto
     */
    'refrigerantTypeId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EquipmentDto
     */
    'refrigerantType'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof EquipmentDto
     */
    'massOfRefrigerantKg'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof EquipmentDto
     */
    'purposeOfEquipmentId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EquipmentDto
     */
    'purposeOfEquipment'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof EquipmentDto
     */
    'coolingTemperature'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof EquipmentDto
     */
    'coolingEffectKw'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof EquipmentDto
     */
    'compressorConnectionPowerKw'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof EquipmentDto
     */
    'liquidCollectorVolume'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof EquipmentDto
     */
    'massAddedLastYearInKg'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof EquipmentDto
     */
    'commissioningDate'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EquipmentDto
     */
    'comments'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof EquipmentDto
     */
    'ordinalNumber'?: number;
    /**
     * 
     * @type {string}
     * @memberof EquipmentDto
     */
    'createdAt'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof EquipmentDto
     */
    'isArchived'?: boolean;
    /**
     * 
     * @type {Array<FileResultDto>}
     * @memberof EquipmentDto
     */
    'files'?: Array<FileResultDto> | null;
    /**
     * 
     * @type {Array<EquipmentActivityDto>}
     * @memberof EquipmentDto
     */
    'equipmentActivities'?: Array<EquipmentActivityDto> | null;
}

