/* tslint:disable */
/* eslint-disable */
/**
 * KGH PROJECT API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { FileResultDto } from './file-result-dto';

/**
 * 
 * @export
 * @interface EquipmentActivityDto
 */
export interface EquipmentActivityDto {
    /**
     * 
     * @type {string}
     * @memberof EquipmentActivityDto
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof EquipmentActivityDto
     */
    'dateOfChange'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EquipmentActivityDto
     */
    'typeOfChangeId'?: string;
    /**
     * 
     * @type {string}
     * @memberof EquipmentActivityDto
     */
    'typeOfChange'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EquipmentActivityDto
     */
    'newOperatorName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EquipmentActivityDto
     */
    'newCoolantId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EquipmentActivityDto
     */
    'newCoolant'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EquipmentActivityDto
     */
    'technicianCertificateNumber'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EquipmentActivityDto
     */
    'createdById'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EquipmentActivityDto
     */
    'createdBy'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EquipmentActivityDto
     */
    'serialNumber'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EquipmentActivityDto
     */
    'branchOfficeName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EquipmentActivityDto
     */
    'comments'?: string | null;
    /**
     * 
     * @type {Array<FileResultDto>}
     * @memberof EquipmentActivityDto
     */
    'files'?: Array<FileResultDto> | null;
}

