/* tslint:disable */
/* eslint-disable */
/**
 * KGH PROJECT API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CodebookTypeEnum } from './codebook-type-enum';
// May contain unused imports in some cases
// @ts-ignore
import { SortingBy } from './sorting-by';

/**
 * 
 * @export
 * @interface GetCodebooksByTypeQuery
 */
export interface GetCodebooksByTypeQuery {
    /**
     * 
     * @type {string}
     * @memberof GetCodebooksByTypeQuery
     */
    'search'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof GetCodebooksByTypeQuery
     */
    'pageNumber'?: number;
    /**
     * 
     * @type {number}
     * @memberof GetCodebooksByTypeQuery
     */
    'pageSize'?: number;
    /**
     * 
     * @type {string}
     * @memberof GetCodebooksByTypeQuery
     */
    'sortBy'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetCodebooksByTypeQuery
     */
    'sortType'?: string | null;
    /**
     * 
     * @type {CodebookTypeEnum}
     * @memberof GetCodebooksByTypeQuery
     */
    'type'?: CodebookTypeEnum;
    /**
     * 
     * @type {Array<SortingBy>}
     * @memberof GetCodebooksByTypeQuery
     */
    'sortings'?: Array<SortingBy> | null;
}

