/* tslint:disable */
/* eslint-disable */
/**
 * KGH PROJECT API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { SortingBy } from './sorting-by';

/**
 * 
 * @export
 * @interface GetActivityLogsQuery
 */
export interface GetActivityLogsQuery {
    /**
     * 
     * @type {number}
     * @memberof GetActivityLogsQuery
     */
    'pageNumber'?: number;
    /**
     * 
     * @type {number}
     * @memberof GetActivityLogsQuery
     */
    'pageSize'?: number;
    /**
     * 
     * @type {string}
     * @memberof GetActivityLogsQuery
     */
    'sortBy'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetActivityLogsQuery
     */
    'sortType'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetActivityLogsQuery
     */
    'fullName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetActivityLogsQuery
     */
    'ip'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof GetActivityLogsQuery
     */
    'logType'?: number;
    /**
     * 
     * @type {string}
     * @memberof GetActivityLogsQuery
     */
    'activity'?: string | null;
    /**
     * 
     * @type {Array<SortingBy>}
     * @memberof GetActivityLogsQuery
     */
    'sortings'?: Array<SortingBy> | null;
}

