/* tslint:disable */
/* eslint-disable */
/**
 * KGH PROJECT API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { SortingBy } from './sorting-by';
// May contain unused imports in some cases
// @ts-ignore
import { UserFilterType } from './user-filter-type';

/**
 * 
 * @export
 * @interface GetUsersQuery
 */
export interface GetUsersQuery {
    /**
     * 
     * @type {number}
     * @memberof GetUsersQuery
     */
    'pageNumber'?: number;
    /**
     * 
     * @type {number}
     * @memberof GetUsersQuery
     */
    'pageSize'?: number;
    /**
     * 
     * @type {string}
     * @memberof GetUsersQuery
     */
    'roleId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetUsersQuery
     */
    'search'?: string | null;
    /**
     * 
     * @type {UserFilterType}
     * @memberof GetUsersQuery
     */
    'filterType'?: UserFilterType;
    /**
     * 
     * @type {Array<SortingBy>}
     * @memberof GetUsersQuery
     */
    'sortings'?: Array<SortingBy> | null;
}

