/* tslint:disable */
/* eslint-disable */
/**
 * KGH PROJECT API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface InstitutionRequest
 */
export interface InstitutionRequest {
    /**
     * 
     * @type {string}
     * @memberof InstitutionRequest
     */
    'name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InstitutionRequest
     */
    'taxNumber'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InstitutionRequest
     */
    'responsiblePersonFullName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InstitutionRequest
     */
    'responsiblePersonFunction'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InstitutionRequest
     */
    'address'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InstitutionRequest
     */
    'place'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof InstitutionRequest
     */
    'municipalityId'?: number;
    /**
     * 
     * @type {string}
     * @memberof InstitutionRequest
     */
    'email'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InstitutionRequest
     */
    'phoneNumber'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InstitutionRequest
     */
    'websiteUrl'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InstitutionRequest
     */
    'contactPerson'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InstitutionRequest
     */
    'contactPersonEmail'?: string | null;
}

