/* tslint:disable */
/* eslint-disable */
/**
 * KGH PROJECT API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Int32ReportResponseDto
 */
export interface Int32ReportResponseDto {
    /**
     * 
     * @type {number}
     * @memberof Int32ReportResponseDto
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof Int32ReportResponseDto
     */
    'name'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Int32ReportResponseDto
     */
    'total'?: number;
    /**
     * 
     * @type {string}
     * @memberof Int32ReportResponseDto
     */
    'stateEntityId'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Int32ReportResponseDto
     */
    'ordinalNumber'?: number;
}

