/* tslint:disable */
/* eslint-disable */
/**
 * KGH PROJECT API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface KGHServiceCompanyDto
 */
export interface KGHServiceCompanyDto {
    /**
     * 
     * @type {string}
     * @memberof KGHServiceCompanyDto
     */
    'id'?: string;
    /**
     * 
     * @type {number}
     * @memberof KGHServiceCompanyDto
     */
    'ordinalNumber'?: number;
    /**
     * 
     * @type {string}
     * @memberof KGHServiceCompanyDto
     */
    'companyName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof KGHServiceCompanyDto
     */
    'licenseId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof KGHServiceCompanyDto
     */
    'licenseDuration'?: string;
    /**
     * 
     * @type {string}
     * @memberof KGHServiceCompanyDto
     */
    'municipality'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof KGHServiceCompanyDto
     */
    'companyType'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof KGHServiceCompanyDto
     */
    'statusDesc'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof KGHServiceCompanyDto
     */
    'nrOfCertifiedServiceTechnicians'?: number;
}

