/* tslint:disable */
/* eslint-disable */
/**
 * KGH PROJECT API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { I18nLanguageCodeDto } from './i18n-language-code-dto';

/**
 * 
 * @export
 * @interface LanguageDto
 */
export interface LanguageDto {
    /**
     * 
     * @type {string}
     * @memberof LanguageDto
     */
    'id'?: string;
    /**
     * 
     * @type {number}
     * @memberof LanguageDto
     */
    'position'?: number;
    /**
     * 
     * @type {string}
     * @memberof LanguageDto
     */
    'i18nCodeId'?: string;
    /**
     * 
     * @type {I18nLanguageCodeDto}
     * @memberof LanguageDto
     */
    'i18nCode'?: I18nLanguageCodeDto;
    /**
     * 
     * @type {boolean}
     * @memberof LanguageDto
     */
    'hasTranslations'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof LanguageDto
     */
    'isDefault'?: boolean;
}

