/* tslint:disable */
/* eslint-disable */
/**
 * DLP PROJECT API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ListShipmentsDto } from './list-shipments-dto';
import { ListTransportManagementDto } from './list-transport-management-dto';

/**
 * 
 * @export
 * @interface ListShipmentsDtoPaginatedList
 */
export interface ListShipmentsDtoPaginatedList {
    /**
     * 
     * @type {Array<ListShipmentsDto>}
     * @memberof ListShipmentsDtoPaginatedList
     */
    'items'?: Array<ListShipmentsDto> | null;
    /**
     * 
     * @type {number}
     * @memberof ListShipmentsDtoPaginatedList
     */
    'pageIndex'?: number;
    /**
     * 
     * @type {number}
     * @memberof ListShipmentsDtoPaginatedList
     */
    'totalPages'?: number;
    /**
     * 
     * @type {number}
     * @memberof ListShipmentsDtoPaginatedList
     */
    'totalCount'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ListShipmentsDtoPaginatedList
     */
    'hasPreviousPage'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ListShipmentsDtoPaginatedList
     */
    'hasNextPage'?: boolean;
}

