/* tslint:disable */
/* eslint-disable */
/**
 * KGH PROJECT API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface LoginResponse
 */
export interface LoginResponse {
    /**
     * 
     * @type {string}
     * @memberof LoginResponse
     */
    'userName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LoginResponse
     */
    'role'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LoginResponse
     */
    'accessToken'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof LoginResponse
     */
    'expiresIn'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof LoginResponse
     */
    'rememberMe'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof LoginResponse
     */
    'shouldShowOnboarding'?: boolean;
     /**
     * 
     * @type {string}
     * @memberof LoginResponse
     */
     'profileImage'?: string | null;
}

