/* tslint:disable */
/* eslint-disable */
/**
 * KGH PROJECT API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { FunctionalityDto } from './functionality-dto';

/**
 * 
 * @export
 * @interface ModuleFunctionalitiesDto
 */
export interface ModuleFunctionalitiesDto {
    /**
     * 
     * @type {number}
     * @memberof ModuleFunctionalitiesDto
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof ModuleFunctionalitiesDto
     */
    'name'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof ModuleFunctionalitiesDto
     */
    'checked'?: boolean;
    /**
     * 
     * @type {Array<FunctionalityDto>}
     * @memberof ModuleFunctionalitiesDto
     */
    'functionalities'?: Array<FunctionalityDto> | null;
}

