/* tslint:disable */
/* eslint-disable */
/**
 * KGH PROJECT API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { OrganizationTypeEnum } from './organization-type-enum';

/**
 * 
 * @export
 * @interface OrganizationRequest
 */
export interface OrganizationRequest {
    /**
     * 
     * @type {string}
     * @memberof OrganizationRequest
     */
    'name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrganizationRequest
     */
    'idNumber'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrganizationRequest
     */
    'taxNumber'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrganizationRequest
     */
    'responsiblePersonFullName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrganizationRequest
     */
    'responsiblePersonFunction'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrganizationRequest
     */
    'country'?: string | null;
     /**
     * 
     * @type {string}
     * @memberof OrganizationRequest
     */
     'countryId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrganizationRequest
     */
    'address'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrganizationRequest
     */
    'place'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrganizationRequest
     */
    'city'?: string | null;
     /**
     * 
     * @type {string}
     * @memberof OrganizationRequest
     */
    'postalCode'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrganizationRequest
     */
    'postCode'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrganizationRequest
     */
    'municipalityId'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationRequest
     */
    'stateEntityId'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationRequest
     */
    'email'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrganizationRequest
     */
    'phoneNumber'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrganizationRequest
     */
    'websiteUrl'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrganizationRequest
     */
    'contactPersonId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrganizationRequest
     */
    'contactPersonFirstName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrganizationRequest
     */
    'contactPersonLastName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrganizationRequest
     */
    'contactPersonEmail'?: string | null;
    /**
     * 
     * @type {OrganizationTypeEnum}
     * @memberof OrganizationRequest
     */
    'organizationType'?: OrganizationTypeEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof OrganizationRequest
     */
    'userGroups'?: Array<string> | null;
}

