/* tslint:disable */
/* eslint-disable */
/**
 * KGH PROJECT API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OwnerOperatorOfEquipmentDto
 */
export interface OwnerOperatorOfEquipmentDto {
    /**
     * 
     * @type {string}
     * @memberof OwnerOperatorOfEquipmentDto
     */
    'id'?: string;
    /**
     * 
     * @type {number}
     * @memberof OwnerOperatorOfEquipmentDto
     */
    'ordinalNumber'?: number;
    /**
     * 
     * @type {string}
     * @memberof OwnerOperatorOfEquipmentDto
     */
    'companyName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OwnerOperatorOfEquipmentDto
     */
    'municipality'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof OwnerOperatorOfEquipmentDto
     */
    'nrOfBranches'?: number;
    /**
     * 
     * @type {number}
     * @memberof OwnerOperatorOfEquipmentDto
     */
    'nrOfEquipments'?: number;
}

