/* tslint:disable */
/* eslint-disable */
/**
 * KGH PROJECT API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { BranchWithEquipmentsDetailsDto } from './branch-with-equipments-details-dto';

/**
 * 
 * @export
 * @interface OwnerOperatorOfEquipmentDetailsDto
 */
export interface OwnerOperatorOfEquipmentDetailsDto {
    /**
     * 
     * @type {string}
     * @memberof OwnerOperatorOfEquipmentDetailsDto
     */
    'companyName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OwnerOperatorOfEquipmentDetailsDto
     */
    'companyEmail'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OwnerOperatorOfEquipmentDetailsDto
     */
    'companyAddress'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OwnerOperatorOfEquipmentDetailsDto
     */
    'companyPlace'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OwnerOperatorOfEquipmentDetailsDto
     */
    'companyWebsite'?: string | null;
        /**
     * 
     * @type {string}
     * @memberof OwnerOperatorOfEquipmentDetailsDto
     */
    'companyActivity'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OwnerOperatorOfEquipmentDetailsDto
     */
    'companyPhoneNumber'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OwnerOperatorOfEquipmentDetailsDto
     */
    'companyIdNumber'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OwnerOperatorOfEquipmentDetailsDto
     */
    'companyTaxNumber'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OwnerOperatorOfEquipmentDetailsDto
     */
    'companyContactPerson'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OwnerOperatorOfEquipmentDetailsDto
     */
    'companyContactPersonEmail'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OwnerOperatorOfEquipmentDetailsDto
     */
    'companyEnrollmentDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof OwnerOperatorOfEquipmentDetailsDto
     */
    'companyMunicipality'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OwnerOperatorOfEquipmentDetailsDto
     */
    'companyCanton'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OwnerOperatorOfEquipmentDetailsDto
     */
    'companyEntity'?: string | null;
    /**
     * 
     * @type {Array<BranchWithEquipmentsDetailsDto>}
     * @memberof OwnerOperatorOfEquipmentDetailsDto
     */
    'branchesWithEquipments'?: Array<BranchWithEquipmentsDetailsDto> | null;
}

