/* tslint:disable */
/* eslint-disable */
/**
 * KGH PROJECT API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PostDto
 */
export interface PostDto {
    /**
     * 
     * @type {string}
     * @memberof PostDto
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof PostDto
     */
    'subject'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PostDto
     */
    'content'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PostDto
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof PostDto
     */
    'createdBy'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PostDto
     */
    'organizationOfCreator'?: string | null;
}

