/* tslint:disable */
/* eslint-disable */
/**
 * KGH PROJECT API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { GeneralReportDto,GeneralReportEntityDto } from "./reports-general-dto";

/**
 *
 * @export
 * @interface GeneralReportDtoPaginatedList
 */

export interface GeneralReportDtoPaginatedList {
  /**
   *
   * @type {Array<GeneralReportDto>}
   * @memberof GeneralReportDtoPaginatedList
   */
  items?: Array<GeneralReportDto> | null;
  /**
   *
   * @type {number}
   * @memberof GeneralReportDtoPaginatedList
   */
  pageIndex?: number;
  /**
   *
   * @type {number}
   * @memberof GeneralReportDtoPaginatedList
   */
  totalPages?: number;
  /**
   *
   * @type {number}
   * @memberof GeneralReportDtoPaginatedList
   */
  totalCount?: number;
  /**
   *
   * @type {boolean}
   * @memberof GeneralReportDtoPaginatedList
   */
  hasPreviousPage?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof GeneralReportDtoPaginatedList
   */
  hasNextPage?: boolean;
}


/**
 *
 * @export
 * @interface GeneralReportEntityDtoPaginatedList
 */

export interface GeneralReportEntityDtoPaginatedList {
  /**
   *
   * @type {Array<GeneralReportEntityDto>}
   * @memberof GeneralReportEntityDtoPaginatedList
   */
  items?: Array<GeneralReportEntityDto> | null;
  /**
   *
   * @type {number}
   * @memberof GeneralReportEntityDtoPaginatedList
   */
  pageIndex?: number;
  /**
   *
   * @type {number}
   * @memberof GeneralReportEntityDtoPaginatedList
   */
  totalPages?: number;
  /**
   *
   * @type {number}
   * @memberof GeneralReportEntityDtoPaginatedList
   */
  totalCount?: number;
  /**
   *
   * @type {boolean}
   * @memberof GeneralReportEntityDtoPaginatedList
   */
  hasPreviousPage?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof GeneralReportEntityDtoPaginatedList
   */
  hasNextPage?: boolean;
}
