/* tslint:disable */
/* eslint-disable */
/**
 * KGH PROJECT API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { CertificateNumberAvailabilityResult } from "./certificate-number-availability-result";
import { QuestionnairesDto } from "./questionnaires-dto";
// May contain unused imports in some cases
// @ts-ignore
import { RequestFileDto } from "./request-file-dto";
// May contain unused imports in some cases
// @ts-ignore
import { RequestStatus } from "./request-status";
// May contain unused imports in some cases
// @ts-ignore
import { RequestType } from "./request-type";

/**
 *
 * @export
 * @interface RequestDetailsDto
 */
export interface RequestDetailsDto {
  /**
   *
   * @type {string}
   * @memberof RequestDetailsDto
   */
  id?: string;
  /**
   *
   * @type {string}
   * @memberof RequestDetailsDto
   */
  idNumber?: string | null;
  /**
   *
   * @type {string}
   * @memberof RequestDetailsDto
   */
  requestId?: string | null;
  /**
   *
   * @type {string}
   * @memberof RequestDetailsDto
   */
  companyName?: string | null;
  /**
   *
   * @type {string}
   * @memberof RequestDetailsDto
   */
  companyEmailAddress?: string | null;
  /**
   *
   * @type {string}
   * @memberof RequestDetailsDto
   */
  companyPhoneNumber?: string | null;
  /**
   *
   * @type {string}
   * @memberof RequestDetailsDto
   */
  websiteUrl?: string | null;
  /**
   *
   * @type {string}
   * @memberof RequestDetailsDto
   */
  taxNumber?: string | null;
  /**
   *
   * @type {string}
   * @memberof RequestDetailsDto
   */
  responsiblePersonFullName?: string | null;
  /**
   *
   * @type {string}
   * @memberof RequestDetailsDto
   */
  responsiblePersonFunction?: string | null;
  /**
   *
   * @type {string}
   * @memberof RequestDetailsDto
   */
  contactPerson?: string | null;
  /**
   *
   * @type {string}
   * @memberof RequestDetailsDto
   */
  contactPersonEmail?: string | null;
  /**
   *
   * @type {string}
   * @memberof RequestDetailsDto
   */
  address?: string | null;
  /**
   *
   * @type {string}
   * @memberof RequestDetailsDto
   */
  place?: string | null;
  /**
   *
   * @type {string}
   * @memberof RequestDetailsDto
   */
  postCode?: string | null;
  /**
   *
   * @type {string}
   * @memberof RequestDetailsDto
   */
  comments?: string | null;
  /**
   *
   * @type {string}
   * @memberof RequestDetailsDto
   */
  municipalityId?: string;
  /**
   *
   * @type {string}
   * @memberof RequestDetailsDto
   */
  municipality?: string | null;
  /**
   *
   * @type {string}
   * @memberof RequestDetailsDto
   */
  canton?: string | null;
  /**
   *
   * @type {string}
   * @memberof RequestDetailsDto
   */
  entity?: string | null;
  /**
   *
   * @type {string}
   * @memberof RequestDetailsDto
   */
  licenseId?: string | null;
  /**
   *
   * @type {string}
   * @memberof RequestDetailsDto
   */
  licenseDuration?: string | null;
  /**
   *
   * @type {Array<CertificateNumberAvailabilityResult>}
   * @memberof RequestDetailsDto
   */
  certificationNumbers?: Array<CertificateNumberAvailabilityResult> | null;
  /**
   *
   * @type {number}
   * @memberof RequestDetailsDto
   */
  totalNumberOfServiceTechnians?: number | null;
  /**
   *
   * @type {boolean}
   * @memberof RequestDetailsDto
   */
  meetsEquipmentRegulations?: boolean | null;
  /**
   *
   * @type {string}
   * @memberof RequestDetailsDto
   */
  createdAt?: string;
  /**
   *
   * @type {RequestType}
   * @memberof RequestDetailsDto
   */
  requestType?: RequestType;
  /**
   *
   * @type {string}
   * @memberof RequestDetailsDto
   */
  requestTypeDesc?: string | null;
  /**
   *
   * @type {RequestStatus}
   * @memberof RequestDetailsDto
   */
  status?: RequestStatus;
  /**
   *
   * @type {string}
   * @memberof RequestDetailsDto
   */
  statusDesc?: string | null;
  /**
   *
   * @type {string}
   * @memberof RequestDetailsDto
   */
  statusText?: string | null;
  /**
   *
   * @type {string}
   * @memberof RequestDetailsDto
   */
  companyType?: string | null;
  /**
   *
   * @type {string}
   * @memberof RequestDetailsDto
   */
  areaOfExpertise?: string | null;
  /**
   *
   * @type {string}
   * @memberof RequestDetailsDto
   */
  businessActivityId?: string | null;
  /**
   *
   * @type {string}
   * @memberof RequestDetailsDto
   */
  businessActivity?: string | null;
  /**
   *
   * @type {string}
   * @memberof RequestDetailsDto
   */
  reviewedByName?: string | null;
  /**
   *
   * @type {string}
   * @memberof RequestDetailsDto
   */
  reviewedAt?: string | null;
  /**
   *
   * @type {Array<RequestFileDto>}
   * @memberof RequestDetailsDto
   */
  attachments?: Array<RequestFileDto> | null;

  /**
   *
   * @type {string}
   * @memberof RequestDetailsDto
   */
  countryName?: string | null;

  /**
   *
   * @type {boolean}
   * @memberof RequestDetailsDto
   */
  hasVatIdAndAcceptsTerms?: boolean | null;

  /**
   *
   * @type {boolean}
   * @memberof RequestDetailsDto
   */
  receiveNews?: boolean | null;

  /**
   *
   * @type {Array<QuestionnairesDto>}
   * @memberof RequestDetailsDto
   */
  questionnaires?: Array<QuestionnairesDto> | null;

  /**
   *
   * @type {string}
   * @memberof RequestDetailsDto
   */
  actionedName?: string | null;

  /**
   *
   * @type {string}
   * @memberof RequestDetailsDto
   */
  actionedAt?: string | null;
}
