/* tslint:disable */
/* eslint-disable */
/**
 * DLP PROJECT API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SubmitOfferTransportManageDto
 */
export interface SubmitOfferTransportManageDto {
    /**
     * 
     * @type {string}
     * @memberof SubmitOfferTransportManageDto
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof SubmitOfferTransportManageDto
     */
    'transportRequestId'?: string;
    /**
     * 
     * @type {number}
     * @memberof SubmitOfferTransportManageDto
     */
    'price'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof SubmitOfferTransportManageDto
     */
    'offerValidityDate'?: number;
    /**
     * 
     * @type {string}
     * @memberof SubmitOfferTransportManageDto
     */
    'estimatedPickupDateTime'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SubmitOfferTransportManageDto
     */
    'estimatedDeliveryDateTime'?: string | null;

    /**
     * 
     * @type {string}
     * @memberof SubmitOfferTransportManageDto
     */
    'estimatedPickupDateTimeFrom'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SubmitOfferTransportManageDto
     */
    'estimatedPickupDateTimeTo'?: string | null;
        /**
     * 
     * @type {string}
     * @memberof SubmitOfferTransportManageDto
     */
    'estimatedDeliveryDateTimeFrom'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SubmitOfferTransportManageDto
     */
    'estimatedDeliveryDateTimeTo'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SubmitOfferTransportManageDto
     */
    'truckTypeId'?: string | null;
}

