/* tslint:disable */
/* eslint-disable */
/**
 * KGH PROJECT API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateRefrigerantTypeCommand
 */
export interface UpdateRefrigerantTypeCommand {
    /**
     * 
     * @type {string}
     * @memberof UpdateRefrigerantTypeCommand
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateRefrigerantTypeCommand
     */
    'name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateRefrigerantTypeCommand
     */
    'ashraeDesignation'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateRefrigerantTypeCommand
     */
    'typeOfCoolingFluid'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateRefrigerantTypeCommand
     */
    'globalWarmingPotential'?: string | null;
}

