/* tslint:disable */
/* eslint-disable */
/**
 * KGH PROJECT API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateCompanyBranchCommand
 */
export interface UpdateCompanyBranchCommand {
    /**
     * 
     * @type {string}
     * @memberof UpdateCompanyBranchCommand
     */
    'branchId'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCompanyBranchCommand
     */
    'branchOfficeName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateCompanyBranchCommand
     */
    'idNumber'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateCompanyBranchCommand
     */
    'address'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateCompanyBranchCommand
     */
    'email'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateCompanyBranchCommand
     */
    'contactPerson'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateCompanyBranchCommand
     */
    'contactPhone'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateCompanyBranchCommand
     */
    'place'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateCompanyBranchCommand
     */
    'municipalityId'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCompanyBranchCommand
     */
    'updatedById'?: string | null;
}

