/* tslint:disable */
/* eslint-disable */
/**
 * KGH PROJECT API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateUserCommand
 */
export interface UpdateUserCommand {
  /**
   *
   * @type {string}
   * @memberof UpdateUserCommand
   */
  id?: string | null;
  /**
   *
   * @type {string}
   * @memberof UpdateUserCommand
   */
  firstName?: string | null;
  /**
   *
   * @type {string}
   * @memberof UpdateUserCommand
   */
  lastName?: string | null;
  /**
   *
   * @type {string}
   * @memberof UpdateUserCommand
   */
  email?: string | null;
  /**
   *
   * @type {string}
   * @memberof UpdateUserCommand
   */
  languageId?: string;
  /**
   *
   * @type {string}
   * @memberof UpdateUserCommand
   */
  municipalityId?: string | null;
  /**
   *
   * @type {string}
   * @memberof UpdateUserCommand
   */
  placeOfBirth?: string | null;
  /**
   *
   * @type {string}
   * @memberof UpdateUserCommand
   */
  address?: string | null;
  /**
   *
   * @type {string}
   * @memberof UpdateUserCommand
   */
  personalNumber?: string | null;
  /**
   *
   * @type {string}
   * @memberof UpdateUserCommand
   */
  phoneNumber?: string | null;
  /**
   *
   * @type {string}
   * @memberof UpdateUserCommand
   */
  organizationId?: string | null;
  /**
   *
   * @type {string}
   * @memberof UpdateUserCommand
   */
  createdById?: string | null;
  /**
   *
   * @type {string}
   * @memberof UpdateUserCommand
   */
  comments?: string | null;
  /**
   *
   * @type {boolean}
   * @memberof UpdateUserCommand
   */
  isCertifiedTechnician?: boolean;
  /**
   *
   * @type {Array<string>}
   * @memberof UpdateUserCommand
   */
  userGroups?: Array<string> | null;
  /**
   *
   * @type {string}
   * @memberof UpdateUserCommand
   */
  profileImageFile?: string | null;
}

