/* tslint:disable */
/* eslint-disable */
/**
 * KGH PROJECT API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateEquipmentCommand
 */
export interface UpdateEquipmentCommand {
    /**
     * 
     * @type {string}
     * @memberof UpdateEquipmentCommand
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateEquipmentCommand
     */
    'branchId'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateEquipmentCommand
     */
    'typeOfEquipmentId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateEquipmentCommand
     */
    'typeOfEquipmentOther'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateEquipmentCommand
     */
    'typeOfCoolingSystemId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateEquipmentCommand
     */
    'typeOfCoolingSystemOther'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateEquipmentCommand
     */
    'manufacturer'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateEquipmentCommand
     */
    'type'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateEquipmentCommand
     */
    'model'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateEquipmentCommand
     */
    'serialNumber'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof UpdateEquipmentCommand
     */
    'yearOfProduction'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateEquipmentCommand
     */
    'dateOfPurchase'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateEquipmentCommand
     */
    'refrigernatTypeId'?: string;
    /**
     * 
     * @type {number}
     * @memberof UpdateEquipmentCommand
     */
    'massOfRefrigerantKg'?: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateEquipmentCommand
     */
    'purposeOfEquipmentId'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof UpdateEquipmentCommand
     */
    'coolingTemperature'?: number;
    /**
     * 
     * @type {number}
     * @memberof UpdateEquipmentCommand
     */
    'coolingEffectKw'?: number;
    /**
     * 
     * @type {number}
     * @memberof UpdateEquipmentCommand
     */
    'compressorConnectionPowerKw'?: number;
    /**
     * 
     * @type {number}
     * @memberof UpdateEquipmentCommand
     */
    'liquidCollectorVolume'?: number;
    /**
     * 
     * @type {number}
     * @memberof UpdateEquipmentCommand
     */
    'massAddedLastYearInKg'?: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateEquipmentCommand
     */
    'commissioningDate'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateEquipmentCommand
     */
    'comments'?: string | null;
}

