/* tslint:disable */
/* eslint-disable */
/**
 * KGH PROJECT API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateEmailOptionsCommand
 */
export interface UpdateEmailOptionsCommand {
    /**
     * 
     * @type {string}
     * @memberof UpdateEmailOptionsCommand
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateEmailOptionsCommand
     */
    'from'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateEmailOptionsCommand
     */
    'smtpHost'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof UpdateEmailOptionsCommand
     */
    'smtpPort'?: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateEmailOptionsCommand
     */
    'smtpUser'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateEmailOptionsCommand
     */
    'smtpPass'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateEmailOptionsCommand
     */
    'createdAt'?: string;
}

