/* tslint:disable */
/* eslint-disable */
/**
 * KGH PROJECT API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UserDto
 */
export interface UserDto {
    /**
     * 
     * @type {number}
     * @memberof UserDto
     */
    'ordinalNumber'?: number;
    /**
     * 
     * @type {string}
     * @memberof UserDto
     */
    'id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserDto
     */
    'firstName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserDto
     */
    'lastName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserDto
     */
    'createdAt'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserDto
     */
    'placeOfBirth'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof UserDto
     */
    'isDeleted'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UserDto
     */
    'isActive'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UserDto
     */
    'isPending'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof UserDto
     */
    'personalNumber'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserDto
     */
    'phoneNumber'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserDto
     */
    'roleName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserDto
     */
    'email'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserDto
     */
    'municipalityId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserDto
     */
    'cantonId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserDto
     */
    'stateEntityId'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserDto
     */
    'organizationId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserDto
     */
    'organizationName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserDto
     */
    'languageId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserDto
     */
    'profileImage'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserDto
     */
    'bannerImage'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserDto
     */
    'comments'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof UserDto
     */
    'isAdmin'?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof UserDto
     */
    'userGroups'?: Array<string> | null;
}

