/* tslint:disable */
/* eslint-disable */
/**
 * KGH PROJECT API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
/**
 * OidcConfigurationApi - axios parameter creator
 * @export
 */
export const OidcConfigurationApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} clientId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        configurationClientIdGet: async (clientId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'clientId' is not null or undefined
            assertParamExists('configurationClientIdGet', 'clientId', clientId)
            const localVarPath = `/_configuration/{clientId}`
                .replace(`{${"clientId"}}`, encodeURIComponent(String(clientId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * OidcConfigurationApi - functional programming interface
 * @export
 */
export const OidcConfigurationApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = OidcConfigurationApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} clientId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async configurationClientIdGet(clientId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.configurationClientIdGet(clientId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * OidcConfigurationApi - factory interface
 * @export
 */
export const OidcConfigurationApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = OidcConfigurationApiFp(configuration)
    return {
        /**
         * 
         * @param {string} clientId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        configurationClientIdGet(clientId: string, options?: any): AxiosPromise<void> {
            return localVarFp.configurationClientIdGet(clientId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for configurationClientIdGet operation in OidcConfigurationApi.
 * @export
 * @interface OidcConfigurationApiConfigurationClientIdGetRequest
 */
export interface OidcConfigurationApiConfigurationClientIdGetRequest {
    /**
     * 
     * @type {string}
     * @memberof OidcConfigurationApiConfigurationClientIdGet
     */
    readonly clientId: string
}

/**
 * OidcConfigurationApi - object-oriented interface
 * @export
 * @class OidcConfigurationApi
 * @extends {BaseAPI}
 */
export class OidcConfigurationApi extends BaseAPI {
    /**
     * 
     * @param {OidcConfigurationApiConfigurationClientIdGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OidcConfigurationApi
     */
    public configurationClientIdGet(requestParameters: OidcConfigurationApiConfigurationClientIdGetRequest, options?: AxiosRequestConfig) {
        return OidcConfigurationApiFp(this.configuration).configurationClientIdGet(requestParameters.clientId, options).then((request) => request(this.axios, this.basePath));
    }
}
